# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: "Carlos Pérez Miguel"
title: PhD and Data Engineer
email: carlos@perezmiguel.es
website: carlos.perezmiguel.es

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: cperezmig
github_username: cperezmig
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: cperezmig
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm __Carlos Pérez-Miguel__. I received the PhD in Computer Science from the University of the Basque Contry, Spain in 2015.
  I have spent the past 16 years developing software in different sectors, both in Industry and Academy.
  In these years, I have been a Backender, a PhD student, a CTO and a Data Engineer.
  I am currently working as an HPC applications specialist at the [Donostia International Physics Center](https://dipc.ehu.eus/).

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Donostia International Physics Center
        link: https://dipc.ehu.eus/
        sub_title: HPC Support and Application Specialist
        caption: June 2024
        quote: >
          Cutting-edge research facility with one of the largest HPC clusters in Spain.
        description: | # this will include new lines to allow paragraphs
            HPC application specialist.
            Technologies: Slurm, Graphana, OpenMP, MPI

      - layout: left
        title: Sparta Commodities
        link: https://www.spartacommodities.com/
        # link_text: boringcompany.com
        sub_title: Senior Data Engineer
        caption: November 2021 - January 2024
        quote: >
          Real time data ingestion and processing for a Series-A scale-up, international Oil and Gas SaaS company.
        description: | # this will include new lines to allow paragraphs
            Senior data engineer working at an international, remote-first, Oil and Gas Data company.
            Main responsibilities:
              - Full software life cycle from conception to application and
                validation of tests.
              - Build and maintain real time data pipelines.
              - Administration of infrastructure.
              - Mentoring of new team members.
              - Tech lead of several projects:
                - New product to improve visualization of historical data.
                - Migration of large amount of real time data and related services from PostgreSQL to Redshift.
                - Design and develop MVP for real time price data ingestion and anomaly detection.

            Technologies: Apache Kafka, Python, Docker, PostgreSQL, Redshift, AWS, Redis, Apache Flink, Vector.dev, Datadog, Apache Iceberg.
      - layout: left
        title: Safecont
        link: https://twitter.com/safecontes
        # link_text: boringcompany.com
        sub_title: Cofounder - CTO - Data Engineer
        caption: September 2015 - February 2021
        quote: >
          Improving the experience of SEO specialists and Online Marketeers by using machine learning and Big Data techniques.
        description: | # this will include new lines to allow paragraphs
          Design tools using Data Mining and Big Data technologies to optimise the on-line visibility of our clients.
          Main responsibilities:
            - Full software life cycle from conception to application and validation of tests.
            - Management of research projects:
                - Duplicate content detection
                - Document classification and clustering
                - PageRank optimization
                - Time-series forecasting
                - Temporal Travel Salesman Problem
            - Administration of several servers.
            - Trainer of new application users and to the new team members.
            - Customer support.

          Technologies: Python, Spark, Scikit-learn, Numpy, Pandas, Dask, Numba, Mongodb, Mesos, Hadoop, Solr, Nutch, Google App Studio, MySQL, REST APIs, Wordpress, CodeIgniter, D3js, Highcharts, Nginx, Apache, Docker, Google Docs API, AWS, Streamlit, SQLite.
      - layout: left
        title: Orange-France Telecom
        #link: https://www.orange.fr
        # link_text: boringcompany.com
        sub_title: System Administrator
        caption: October 2007 - August 2008
        quote: >
          Sysadmin for the bistest telecom company on France.
        description: | # this will include new lines to allow paragraphs
          Administration and integration of Orange's Address Book web applications.
          Main responsibilities:
              - Administration of several web servers and load balancers.
              - Validation of integration tests.
              - Partnership with several developer teams at India and France.
              - Partnership with in-house production teams.

          Technologies: Apache, Tomcat, Perl, Bash, VMWare, Java, Redhat Linux.
      - layout: left
        title: Crédit Agricole CIB
        #link: https://www.orange.fr
        # link_text: boringcompany.com
        sub_title: Back Office Application Developer
        caption: May 2006 - September 2007
        quote: >
          Backoffice developer
        description: | # this will include new lines to allow paragraphs
          Main developer of the application Suprema, Calyon’s Back Office application for titles borrowing and lending.
          Main responsibilities:
            - Full software life cycle from conception to application and validation of tests.
            - In-house financial libraries C++ Development, evolutions and bug fixing.
            - Trainer of new application users and to the new team members.
            - Partnership with several teams including Tokyo and New York.
            - Customer support.

          Technologies: C, C++, Java, Shell, SQL, Unix.
      - layout: left
        title: KUTXABANK
        sub_title: Embedded Systems Developer
        caption: October 2005 - May 2006
        #quote: >
          #Sysadmin for the bistest telecom company on France.
        description: | # this will include new lines to allow paragraphs
          Main responsibilities:
            - Analysis and design of an embedded application for processing banking operations.
            - Inhouse financial libraries C Development.
            - Full software life cycle from conception to application and validation of tests.
            - Trainer of new application users.

          Technologies: C, Java, Debian Linux, XML, Shell

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Basque Country
        caption: 2010 - 2015
        sub_title: PhD in Computer Science
        quote: >
          PhD thesis: "High Throughput Computing over Peer-to-peer Networks"
        description: | # this will include new lines to allow paragraphs
          Advisors: J. Miguel-Alonso and A. Mendiburu

          Viva: 18/06/2015

          Cum Laude, International mention with a visit to the NICAL group, University of Science and Technology of China, Hefei, China (January-April 2013).

          Partially funded by an Doctoral Grant from the Basque Government.
      - layout: left
        title: University of Basque Country
        caption: 2008 - 2010
        sub_title: MSc in Distributed Systems
        quote: >
          MSc thesis: "Parallelization of Estimation of Distribution Algorithms over the Cell Broadband Engine"
        description: | # this will include new lines to allow paragraphs
          Parallelization and vectorization of scientific codes over several parallel architectures.
      - layout: left
        title: University of Basque Country
        caption: 1999 - 2005
        sub_title: MSc in Computer Science
        quote: >
          MSc thesis: "Peer-to-peer file sharing system"
        #Main subjects: Mathematics, Statistics, Physics, Programming, Operational Research, Telecommunication Systems, Digital and Analogical Electronics.
        description: | # this will include new lines to allow paragraphs
          Design, analysis and assessment of IT systems in general, considering the different aspects of management, orgranisation and direction of IT projects, maintenance of equipment and infrastructure, artificial intelligence, parallelism and mass management of information.

          9 months in Université de Versailles-Saint Quentin en Yvelines, Versailles, France (Erasmus Grant).
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Journals
        description: | # this will include new lines to allow paragraphs
          - Pérez-Miguel, C., Miguel-Alonso, J. and Mendiburu, A. "Competition-based failure-aware scheduling for High-Throughput Computing systems on peer-to-peer networks". **Cluster Computing, 18(3), 1229-1249, 2015.**
          - Pérez-Miguel, C., Miguel-Alonso, J. and Mendiburu, A. "Modeling the availability of Cassandra". **Journal of Parallel and Distributed Computing, 86, 29-44, 2015.**
          - Pérez-Miguel, C., Miguel-Alonso, J. and Mendiburu, A. "High throughput computing over peer-to-peer networks". **Future Generation Computer Systems, 29(1), 352-360, 2013.**
          - Pérez-Miguel, C., Miguel-Alonso, J. and Mendiburu, A. "Porting Estimation of Distribution Algorithms to the Cell Broadband Engine". **Parallel Computing, 36(10-11), 618-634, 2010.**
      - layout: left
        title: Conferences
        description: | # this will include new lines to allow paragraphs
          - Pérez-Miguel, C., Miguel-Alonso, J. and Mendiburu, A. "Sistemas HTC sobre redes P2P". **XXI Jornadas de Paralelismo, CEDI, Valencia, Spain, 2010.**
          - Pérez-Miguel, C., Miguel-Alonso, J. and Mendiburu, A. "Porting Estimation of Distribution Algorithms to the Cell Broadband Engine". **Best Paper Award.** **Second International Workshop on Parallel Architectures and Bioinspired Algorithms (WPABA), Raleigh, NC, USA, 2009.**
          - Pérez-Miguel, C., Miguel-Alonso, J. and Mendiburu, A. "Evaluating the cell broadband engine as a platform to run estimation of distribution algorithms". **GECCO, Montreal, Canada, 2009.**
          - Pérez-Miguel, C., Miguel-Alonso, J. and Mendiburu, A. "Evaluation of the Cell Broadband Engine running Continuous Estimation of Distribution Algorithms". **XX Jornadas de Paralelismo. A Coruña. Spain. 2009.**
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in parallel and distributed systems, some of my other interests and hobbies are:
      - Traveling
      - Reading
      - Bikes
      - Bread bakery

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
